baseURL = 'https://jamiesecops.github.io/'
languageCode = 'en-us'
title = 'Giga Genghis'


copyright = "Â© jamieSecOps"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Practical Cyber Threat Intelligence"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jamieSecOps"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4